name: Debug Test
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show detailed file info
        run: |
          echo "All files with extensions:"
          ls -la
          echo "---"
          echo "Files containing 'process':"
          ls -la *process*
          echo "---" 
          echo "Try running the files directly:"
          python process_ranks_full || echo "Failed without .py"
          python process_ranks_full.py || echo "Failed with .py"
