name: Debug Test
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show files
        run: |
          echo "Current directory:"
          pwd
          echo "Files here:"
          ls -la
          echo "Python files:"
          ls -la *.py || echo "No Python files found"
